# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    form:
        csrf_protection:
            enabled: true
            field_name: '_csrf_token'

    session:
        handler_id: session.handler.native_file
        save_path: '/tmp/sessions'
        cookie_secure: auto
        cookie_samesite: lax

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
